# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def commentPods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Action'
  pod 'RxTest'
  pod 'RxBlocking'
end

target 'DemoCleanArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoCleanArchitecture
  pod 'Moya'
  commentPods
end

target 'DemoCleanArchitectureTests' do
  commentPods
end
