# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoCleanArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoCleanArchitecture
  pod 'Moya'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Action'
end
